### ISSUE TITLE
Kubernetes version in this template is obsolete.

### ISSUE THREAD

**Issue by jfinleynz** [mspnp/solution-architectures#5]
The kubernetes version (1.8.1) used in the devops-aks template is no longer supported/deployable.

I have tested using 1.12.5 (the latest supported version), and it appears to deploy.

**Comment by macmizer** [comment]
> The kubernetes version (1.8.1) used in the devops-aks template is no longer supported/deployable.
> I have tested using 1.12.5 (the latest supported version), and it appears to deploy.

I am running these GitHub via a url while on a cloud shell in Azure.  I was getting an error that I believe is related to this obsolete Kubernetes version.  Now how may I use these files when I can't edit them on GitHub?  In other words, I point my code, via a Microsoft AZ301 training course and the url points to this repo.

**Comment by macmizer** [comment]
I am running these GitHub via a url while on a cloud shell in Azure. I was getting an error that I believe is related to this obsolete Kubernetes version. Now how may I use these files when I can't edit them on GitHub? In other words, I point my code, via a Microsoft AZ301 training course and the url points to this repo.

**Comment by jfinleynz** [comment]
> I am running these GitHub via a url while on a cloud shell in Azure. I was getting an error that I believe is related to this obsolete Kubernetes version. Now how may I use these files when I can't edit them on GitHub? In other words, I point my code, via a Microsoft AZ301 training course and the url points to this repo.

You've got a couple of choices--download the file into your cloud shell storage account and edit the template, then use the modified template to deploy (you'll have to use the switch for a template path, not a template uri).

Alternatively, feel free to use a fork I made for exactly that reason: 

https://raw.githubusercontent.com/jfinleynz/solution-architectures/master/apps/devops-with-aks/azuredeploy.json

Feel free to reference and use as is where is. I have no plans to actively maintain that over the long time, but it was a workaround for me in the course that was easy to tell students to do.

**Comment by macmizer** [comment]
Thank you for the quick reply. Was it expecting that.
Will give it a try.

Have a great day
Rob


________________________________
