### ISSUE TITLE
HPC ARM Template Uses Unrealistic Sizes

### ISSUE THREAD

**Issue by ciphertxt** [mspnp/solution-architectures#8]
The template at <https://github.com/mspnp/solution-architectures/blob/master/hpc/batchcreatewithpools.json> has a hard coded variable which sets the size of VMs in the batch pool to `Standard_A2_v2`. 

This goes against the public guidance included in the Azure Architecture Center and the very [article](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/video-rendering#machine-sizes-available-for-azure-batch) this template is linked from.

I suggest that the template be updated to match the [guidance in the architecture center](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general) and to maintain cost controls a [General Purpose VM size](https://docs.microsoft.com/azure/virtual-machines/windows/sizes-general) is used.

**Comment by ckittel** [comment]
Thanks for the feedback Scott.  The observation that an A2 v2 is probably not suitable for most 3D video rendering HPC workloads is spot on.  The intent wasn't to make a specific SKU recommendation on behalf of any customers, it was to keep costs low while customers explore the services and topology of this example.

The ARM template referenced in the article and in your post matches the [description laid out in the article](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/video-rendering#deploy-the-components) of using A2 v2 VMs for the _sample_ deployment.  A2 v2 is indeed considered a [General Purpose VM](https://docs.microsoft.com/en-us/azure/virtual-machines/sizes-general), so the guidance is constant in that regard.  The documentation goes into more depth on [choosing a compute SKU](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/video-rendering#machine-sizes-available-for-azure-batch) that is fit for your specific purpose.

Changing the SKU in the template would necessitate the description of the _sample_ to be updated in the referenced article to stay in sync.

I'm going to close this out.  However, if you wish to reopen with a suggestion on a more appropriate, yet cost-constrained, SKU for the sample please do so.
